import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '../../../shared/theme/theme';

export const st = StyleSheet.create({
  // Hero
  hero: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
    overflow: 'hidden',
  },
  heroDeco1: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: colors.navy3,
    opacity: 0.4,
    top: -60,
    right: -60,
  },
  heroDeco2: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.gold,
    opacity: 0.06,
    bottom: -20,
    left: 40,
  },
  heroTopRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.lg },
  avatarWrap: { position: 'relative', width: 52, height: 52 },
  avatarRing: {
    position: 'absolute',
    inset: -3,
    borderRadius: radius.full,
    borderWidth: 2,
    borderColor: colors.gold + '80',
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: radius.full,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontWeight: '800', fontSize: 18 },
  rolePill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.gold + '2A',
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginBottom: 4,
  },
  rolePillText: { color: colors.gold3, fontSize: 10, fontWeight: '700', letterSpacing: 1.2 },
  heroName: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', letterSpacing: -0.3 },
  heroEmail: { color: '#8FA5BA', fontSize: 12, marginTop: 2 },
  logoutBtn: {
    width: 38,
    height: 38,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  heroStatsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  heroStat: {
    width: '48%',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: spacing.md,
    gap: 4,
  },
  heroStatValue: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', marginTop: 6 },
  heroStatLabel: { color: '#7A94B8', fontSize: 11, fontWeight: '500' },

  // Charts
  chartsRow: { flexDirection: 'row', gap: spacing.sm },
  chartCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.md,
    ...shadows.md,
    alignItems: 'center',
  },
  chartTitle: {
    alignSelf: 'flex-start',
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  chartEmptyText: { fontSize: 12, color: colors.textTertiary, marginTop: 8 },
  legendWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 10, color: colors.textSecondary },

  // Section
  section: { paddingHorizontal: spacing.lg, marginTop: spacing.lg },
  sectionRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  sectionTitleLine: { width: 3, height: 16, borderRadius: 2, backgroundColor: colors.gold },
  sectionTitle: { fontSize: 13, fontWeight: '700', color: colors.textPrimary, letterSpacing: 0.2, flex: 1 },
  countPill: {
    backgroundColor: colors.navy + '15',
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  countPillText: { fontSize: 11, fontWeight: '700', color: colors.navy },

  // KPI
  kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  kpiCard: {
    width: '48%',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderTopWidth: 3,
    ...shadows.sm,
  },
  kpiCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  kpiIconWrap: {
    width: 30,
    height: 30,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  kpiAlertPip: {
    position: 'absolute',
    top: -3,
    right: -3,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#DC2626',
    borderWidth: 1.5,
    borderColor: colors.surface,
  },
  kpiValue: { fontSize: 26, fontWeight: '800', letterSpacing: -0.5, marginVertical: 4 },
  kpiLabel: { fontSize: 11, color: colors.textSecondary, fontWeight: '600', flex: 1, marginRight: 4, lineHeight: 15 },
  kpiFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
  },
  kpiStatusDot: { width: 6, height: 6, borderRadius: 3 },
  kpiNote: { fontSize: 10, fontWeight: '600' },
  kpiChartsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  kpiChartCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.md,
    ...shadows.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  kpiChartTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    marginBottom: 2,
  },

  // Shortcuts
  shortcutsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  shortcutTile: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.sm,
    alignItems: 'center',
    ...shadows.xs,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  shortcutIcon: {
    width: 44,
    height: 44,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  shortcutLabel: { fontSize: 10, fontWeight: '600', color: colors.textPrimary, textAlign: 'center' },

  // Cards
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.md,
    marginBottom: spacing.sm,
    ...shadows.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cardHead: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, marginBottom: spacing.sm },
  cardIconWrap: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.navy + '0E',
  },
  cardTitle: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  cardSub: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  cardMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.xs },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.borderLight,
    borderRadius: radius.full,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  metaChipText: { fontSize: 11, color: colors.textSecondary },

  // Badge
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: 'flex-start',
  },
  badgeDot: { width: 6, height: 6, borderRadius: 3 },
  badgeText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.2 },

  // Info table
  infoTable: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    overflow: 'hidden',
    marginBottom: spacing.sm,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs + 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.surfaceAlt,
  },
  infoKey: { fontSize: 12, color: colors.textSecondary },
  infoVal: { fontSize: 12, color: colors.textPrimary, fontWeight: '600' },

  noteText: { fontSize: 12, color: colors.textSecondary, fontStyle: 'italic', marginBottom: spacing.sm },

  // Action buttons
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  actionBtnLabel: { fontSize: 12, fontWeight: '700' },

  // Keys
  keyCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...shadows.xs,
  },
  keyCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xs },
  keyCardLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  keyPlanBadge: { borderRadius: radius.full, paddingHorizontal: 10, paddingVertical: 3 },
  keyPlanText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.4 },
  keyCode: { fontSize: 15, fontWeight: '800', color: colors.textPrimary, letterSpacing: 1 },
  keyMeta: { fontSize: 12, color: colors.textSecondary, marginBottom: 4 },
  keyOwner: { fontSize: 12, color: colors.textTertiary },
  keyStatsRow: { flexDirection: 'row', justifyContent: 'center', gap: spacing.lg, marginTop: spacing.xs },
  keyStat: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  keyStatText: { fontSize: 12, color: colors.textSecondary, fontWeight: '600' },

  // Empty state
  emptyState: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderStyle: 'dashed',
  },
  emptyText: { fontSize: 13, color: colors.textTertiary, textAlign: 'center' },
});
